# ---------------------------------------------------------------------------
# File        : Makefile.mac_dual
# Description : The cocotb set for the MAC group with two clients, which is where a per
#               client reset request is shown not to reach its sibling.
# Author      : Xiaohai Li <haixiaolee@gmail.com>
# Language    : Makefile
#
#
# Copyright (c) 2026 Xiaohai Li <haixiaolee@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause-Views
# ---------------------------------------------------------------------------

SIM_BUILD ?= sim_build_seam_mac_dual
COCOTB_RESULTS_FILE ?= results_seam_mac_dual.xml

TOPLEVEL_LANG ?= verilog
SIM           ?= verilator

HERE    := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

THIS_MK := $(lastword $(MAKEFILE_LIST))
MODEL_DIR := $(HERE)/../model
RTL_DIR := $(HERE)/../../rtl

VERILOG_SOURCES := \
  $(RTL_DIR)/ctl/dcmac_ctl_pkg.sv \
  $(RTL_DIR)/ctl/dcmac_ctl_seq.sv \
  $(RTL_DIR)/ctl/dcmac_link_wdt.sv \
  $(RTL_DIR)/ctl/dcmac_link_sample.sv \
  $(RTL_DIR)/ctl/wdt.sv \
  $(RTL_DIR)/ctl/dcmac_axil_exec.sv \
  $(RTL_DIR)/ctl/dcmac_axil_arb.sv \
  $(RTL_DIR)/ctl/dcmac_link_ctl.sv \
  $(RTL_DIR)/dcmac_seg_axis_adapter.sv \
  $(RTL_DIR)/eth_axis_dwidth.sv \
  $(MODEL_DIR)/eth_axis_async_fifo.sv \
  $(RTL_DIR)/dcmac_axis_frame_fifo.sv \
  $(MODEL_DIR)/tx_frame_fifo.sv \
  $(RTL_DIR)/ctl/dcmac_mac_ctl_fsm.sv \
  $(RTL_DIR)/dcmac_axis_adapter.sv \
  $(RTL_DIR)/dcmac_sync2.sv \
  $(RTL_DIR)/gt_rst_req_gate.sv \
  $(RTL_DIR)/dcmac_port.sv \
  $(RTL_DIR)/dcmac_mac_group.sv \
  $(RTL_DIR)/dcmac_phy_model.sv

TOPLEVEL := dcmac_mac_group
MODULE   := test_dcmac_mac_dual

export PYTHONPATH := $(HERE):$(HERE)/..:$(PYTHONPATH)

export N_CLIENT  ?= 2
export N_SEG     ?= 2
export SEG_W     ?= 128
export PTP_TS_EN ?= 0
export PTP_TS_W  ?= 80
export TX_TAG_W  ?= 0
export PORT_MAX  ?= 6
export NPORTS    ?= 1
export ANCHOR_0  ?= 0

export ANCHOR_1  ?= 1

export LOOPBACK_MODE ?= 1

export CTL_CYC_PER_MS ?= 4

export EN_DPRST_SYNC ?= 1

export EN_DPRST_GATE      ?= 1
export DPRST_PULSE_CYC    ?= 16
export DPRST_SETTLE_CYC   ?= 20
export DPRST_DONE_TMO_CYC ?= 200

export LINK_WDT_MS     ?= 8
export LINK_WDT_MS_MIN ?= 1

export T_SAMPLE_MS     ?= 1
export LINK_WDT_MS_MAX ?= 60000
export LINK_CONFIRM_N  ?= 2
export ESC_MAX_STAGE   ?= 3
export T_RXDP_MS_ESC   ?= 2
export EN_RR_POLL      ?= 1

export NIA_BRINGUP_US ?= 400
export NIA_TEST_US    ?= 600
export NIA_WALL_SECS  ?= 600

SEED ?=
ifneq ($(SEED),)

    export RANDOM_SEED        := $(SEED)
    export COCOTB_RANDOM_SEED := $(SEED)
endif

ifeq ($(SIM),verilator)
    TRACE ?= 0
    ifeq ($(TRACE),1)
        EXTRA_ARGS += --trace --trace-structs
    endif

    EXTRA_ARGS += -Wno-WIDTH -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC -Wno-UNOPTFLAT \
                  -Wno-CASEINCOMPLETE -Wno-DECLFILENAME -Wno-PINMISSING

    COMPILE_ARGS += -GN_CLIENT=$(N_CLIENT) -GN_SEG=$(N_SEG) -GSEG_W=$(SEG_W)
    COMPILE_ARGS += -GPORT_MAX=$(PORT_MAX) -GNPORTS=$(NPORTS)
    COMPILE_ARGS += -GANCHOR_0=$(ANCHOR_0) -GANCHOR_1=$(ANCHOR_1)
    COMPILE_ARGS += -GPTP_TS_EN=$(PTP_TS_EN) -GPTP_TS_W=$(PTP_TS_W) -GTX_TAG_W=$(TX_TAG_W)
    COMPILE_ARGS += -GLOOPBACK_MODE=$(LOOPBACK_MODE) -GCTL_CYC_PER_MS=$(CTL_CYC_PER_MS)
    COMPILE_ARGS += -GEN_DPRST_SYNC=$(EN_DPRST_SYNC)

    COMPILE_ARGS += -GEN_DPRST_GATE=$(EN_DPRST_GATE) -GDPRST_PULSE_CYC=$(DPRST_PULSE_CYC)
    COMPILE_ARGS += -GDPRST_SETTLE_CYC=$(DPRST_SETTLE_CYC) -GDPRST_DONE_TMO_CYC=$(DPRST_DONE_TMO_CYC)
    COMPILE_ARGS += -GLINK_WDT_MS=$(LINK_WDT_MS) -GLINK_WDT_MS_MIN=$(LINK_WDT_MS_MIN) \
                    -GT_SAMPLE_MS=$(T_SAMPLE_MS)
    COMPILE_ARGS += -GLINK_WDT_MS_MAX=$(LINK_WDT_MS_MAX) -GLINK_CONFIRM_N=$(LINK_CONFIRM_N)
    COMPILE_ARGS += -GESC_MAX_STAGE=$(ESC_MAX_STAGE)
    COMPILE_ARGS += -GEN_RR_POLL=$(EN_RR_POLL)

    ifeq ($(FF_BRAM),1)
        COMPILE_ARGS += +define+DCMAC_FRAME_FIFO_BRAM
    endif
endif

export FF_BRAM ?= 0

COCOTB_HDL_TIMEUNIT      ?= 1ns
COCOTB_HDL_TIMEPRECISION ?= 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim

.PHONY: monitor control rxonly stage2

rxonly:
	$(MAKE) -f $(THIS_MK) ESC_MAX_STAGE=1

stage2:
	$(MAKE) -f $(THIS_MK) ESC_MAX_STAGE=2

monitor:
	@echo "NIA_NOOP Makefile.mac_dual: 'monitor' is superseded by.. - every image supervises now. Running the default variant."
	$(MAKE) -f $(THIS_MK)

control:
	@echo "NIA_NOOP Makefile.mac_dual: 'control' (EN_MONITOR=0) no longer exists. The control variant is 'rxonly' (ESC_MAX_STAGE=1). Running that."
	$(MAKE) -f $(THIS_MK) ESC_MAX_STAGE=1
