# ---------------------------------------------------------------------------
# File        : Makefile.link_latched_view
# Description : The cocotb set for the latched view of the link status, which is a
#               declared negative control and is expected to fail.
# Author      : Xiaohai Li <haixiaolee@gmail.com>
# Language    : Makefile
#
#
# Copyright (c) 2026 Xiaohai Li <haixiaolee@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause-Views
# ---------------------------------------------------------------------------

NIA_EXPECT := fail

SIM_BUILD ?= sim_build_ctl_seq_link_defect
COCOTB_RESULTS_FILE ?= results_ctl_seq_link_defect.xml

TOPLEVEL_LANG ?= verilog
SIM           ?= verilator

HERE    := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
THIS_MK := $(lastword $(MAKEFILE_LIST))
RTL_DIR := $(HERE)/../../rtl/ctl

COYOTE_CTL_SIM ?= $(HERE)
CTL_SEQ_SRC ?= $(RTL_DIR)/dcmac_ctl_seq.sv

VERILOG_SOURCES := \
  $(RTL_DIR)/dcmac_ctl_pkg.sv \
  $(CTL_SEQ_SRC)

TOPLEVEL := dcmac_ctl_seq
MODULE   := test_dcmac_ctl_seq_link_latched

export PYTHONPATH := $(HERE):$(HERE)/..:$(COYOTE_CTL_SIM):$(PYTHONPATH)
export COYOTE_CTL_SIM

export N_GROUP     ?= 2
export ANCHOR      ?= 0
export ANCHOR_1    ?= 1
export NPORTS      ?= 1
export CYC_PER_MS  ?= 20
export POLL_TRIES  ?= 3
export RATE_CODE   ?= 0
export RATE_FIELD  ?= 4
export DONE_MASK   ?= 3
GAP_MS      ?= 50

export EN_RR_POLL      ?= 1
export LINK_CONFIRM_N   ?= 2

export NIA_WALL_SECS      ?= 900
export NIA_MIN_CYC_PER_MS ?= 20

SEED ?=
ifneq ($(SEED),)
    export RANDOM_SEED        := $(SEED)
    export COCOTB_RANDOM_SEED := $(SEED)
endif

ifeq ($(SIM),verilator)
    EXTRA_ARGS += -Wno-WIDTH -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC -Wno-UNOPTFLAT \
                  -Wno-CASEINCOMPLETE -Wno-UNSIGNED -Wno-CMPCONST -Wno-SELRANGE
    COMPILE_ARGS += -GNPORTS=$(NPORTS) -GANCHOR=$(ANCHOR) \
                    -GN_GROUP=$(N_GROUP) -GANCHOR_1=$(ANCHOR_1) \
                    -GCYC_PER_MS=$(CYC_PER_MS) -GPOLL_TRIES=$(POLL_TRIES) \
                    -GRATE_CODE=$(RATE_CODE) -GRATE_FIELD=$(RATE_FIELD) \
                    -GDONE_MASK=$(DONE_MASK) -GT_PORT_CHAN_GAP_MS=$(GAP_MS) \
                    -GEN_RR_POLL=$(EN_RR_POLL) \
                    -GLINK_CONFIRM_N=$(LINK_CONFIRM_N)
endif

COCOTB_HDL_TIMEUNIT      ?= 1ns
COCOTB_HDL_TIMEPRECISION ?= 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim

.PHONY: exportoff
exportoff:
	$(MAKE) -f $(THIS_MK) LINK_CONFIRM_N=1
