# ---------------------------------------------------------------------------
# File        : Makefile.sim
# Description : The stand-in cocotb makefile the stub install points at, which lets a
#               simulation set be parsed and listed without cocotb present.
# Author      : Xiaohai Li <haixiaolee@gmail.com>
# Language    : Makefile
#
#
# Copyright (c) 2026 Xiaohai Li <haixiaolee@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause-Views
# ---------------------------------------------------------------------------
